d<- read.table("household_power_consumption.txt", sep=";", header=TRUE, colClasses=c("character", "character", rep("numeric",7)),na="?")
d$Date<-as.Date(d$Date,"%d/%m/%Y")
d<-subset(d,d$Date>="2007-02-01" & d$Date<="2007-02-02")
d$Time<-strptime(paste(d$Date,d$Time),format="%Y-%m-%d %H:%M:%S")
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(d$Time,d$Global_active_power, type= "l",ylab="Global Active Power (kilowatts)",xlab="")
plot(d$Time,d$Voltage,type="l",ylab="Voltage",xlab="datetime")
plot(d$Time,d$Sub_metering_1,type="l",ylab="Energy Sub Metering",xlab="")
lines(d$Time, d$Sub_metering_2, col="red")
lines(d$Time, d$Sub_metering_3, col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o",cex=0.5)
plot(d$Time,d$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()

