d<- read.table("household_power_consumption.txt", sep=";", header=TRUE, colClasses=c("character", "character", rep("numeric",7)),na="?")
d$Date<-as.Date(d$Date,"%d/%m/%Y")
d<-subset(d,d$Date>="2007-02-01" & d$Date<="2007-02-02")
d$Time<-strptime(paste(d$Date,d$Time),format="%Y-%m-%d %H:%M:%S")
plot(d$Time,d$Sub_metering_1,type="l",ylab="Energy Sub Metering",xlab="")
lines(d$Time, d$Sub_metering_2, col="red")
lines(d$Time, d$Sub_metering_3, col="blue")
legend("topright",col=c("black", "red", "blue"), legend =c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty=1, cex=0.5)
dev.copy(png,file="plot3.png",width = 480, height = 480)
dev.off()
